# Uncomment the next line to define a global platform for your project
# platform :ios, '10.0'

target 'sampleiOS' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
#platform :ios, '11.2'
  # Pods for sampleiOS
        pod 'EnxRTCiOS', '2.3.14'
        pod 'Socket.IO-Client-Swift', '~> 15.2.0'
        pod 'SVProgressHUD'
        pod 'ReachabilitySwift'
        pod 'Crashlytics'
       # pod 'MMWormhole', '~> 2.0.0'
       

  target 'sampleiOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'sampleiOSUITests' do
    inherit! :search_paths
    # Pods for testing
  end
  target 'BroadcastExtension' do
    inherit! :search_paths
     #Pods for BroadcastExtension
     #platform :ios, '11.0'
     #  project 'sampleiOS.xcodeproj'
  end
  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['APPLICATION_EXTENSION_API_ONLY'] = 'No'
	config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
      end
    end
  end
end
